

POST http://localhost:3000/hangman/james

###

GET http://localhost:3000/hangman/james

###

PATCH http://localhost:3000/hangman/james
// have to send user id here, then set the game fields
// so...on create login page, create user.  then when user starts each game, if one doesnt already exist, create one and map id to the user.  then on playing each game, fetches or creates a game for the user
Content-Type: application/json

{  
    "isWin": false
}


